# Generated by Django 4.2.7 on 2023-12-29 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_attendence'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=255)),
                ('mark', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
