# Generated by Django 4.2.7 on 2023-12-29 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_semmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='semmark',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Home.student'),
            preserve_default=False,
        ),
    ]
