# Generated by Django 4.2.7 on 2023-12-29 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_semmark_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semmark',
            name='mark',
            field=models.FloatField(),
        ),
    ]
